version: "3.9"

services:
  db:
    image: postgres:15
    container_name: studentdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studentdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: student-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: studentdb
      PORT: 5000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  db_data:
